"""empty message

Revision ID: 16c1d62682aa
Revises: b578160f97be
Create Date: 2018-07-30 21:23:06.822308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c1d62682aa'
down_revision = 'b578160f97be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_index(op.f('ix_owners_username'), 'owners', ['username'], unique=True)
    op.add_column('books', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('books', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'owners', ['owner_id'], ['owner_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'owner_id')
    op.drop_column('books', 'date_added')
    op.drop_index(op.f('ix_owners_username'), table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
