"""empty message

Revision ID: 6eddc7dc4828
Revises: b578160f97be
Create Date: 2018-07-03 11:25:53.828433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eddc7dc4828'
down_revision = 'b578160f97be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_index(op.f('ix_owners_username'), 'owners', ['username'], unique=True)
    op.create_foreign_key(None, 'books', 'owners', ['owner_id'], ['owner_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_owner_id_fkey', 'books', 'owner', ['owner_id'], ['owner_id'])
    op.create_table('owner',
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('owner_id', name='owner_pkey')
    )
    op.create_index('ix_owner_username', 'owner', ['username'], unique=True)
    op.create_index('ix_owner_email', 'owner', ['email'], unique=True)
    op.drop_index(op.f('ix_owners_username'), table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
